name: "Deploy to FTP"

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v3.6.0

      - name: "Install dependencies"
        run: "cd source && npm i"
        shell: bash

      - name: "Build Tailwind"
        run: "cd source && npm run build"
        shell: bash
        
      - name: "Send to FTP"
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          local-dir: ./source/static
          server-dir: ./BockUfSteil/
          dangerous-clean-slate: true
